apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bareuptime-backend

resources:
  - manifests.yaml
  - ingress.yaml

commonLabels:
  app: status-pages
  component: frontend
  environment: production
  managed-by: argocd

# Images to track (for ArgoCD image updater)
images:
  - name: ghcr.io/bareuptime/status-pages
    newTag: latest
